const $ = (s, r=document) => r.querySelector(s);
const app = $('#app');
const calls = [
  {time:'08:14', icon:'✓', title:'Okänt nummer godkändes', desc:'AI tog samtalet först, verifierade ärendet och kopplade vidare.', risk:'Låg', cls:'low'},
  {time:'10:42', icon:'!', title:'BankID-försök blockerades', desc:'Uppringaren bad om BankID och försökte skapa tidspress. Anna notifierades.', risk:'Hög', cls:'high'},
  {time:'Igår', icon:'?', title:'Leveranssamtal screenades', desc:'AI bad om ärendenummer. Samtalet släpptes inte vidare.', risk:'Medel', cls:'med'},
  {time:'Mån', icon:'✓', title:'Vårdcentral släpptes igenom', desc:'Numret matchade betrodd kategori och kopplades vidare direkt.', risk:'Låg', cls:'low'}
];
const family = [
  {name:'Anna Svensson', role:'Dotter', status:'Primär anhörig', icon:'A'},
  {name:'Peter Svensson', role:'Son', status:'Backup', icon:'P'},
  {name:'Karin Lund', role:'Granne', status:'Trygghetskontakt', icon:'K'}
];
function nav(){return `<nav class="nav">${[['home','⌂','Hem'],['protection','◉','Skydd'],['calls','☎','Samtal'],['family','👥','Familj'],['reports','▦','Rapport']].map(([id,ico,label])=>`<button data-page="${id}" data-label="${label}" class="${id==='home'?'active':''}">${ico}<span> ${label}</span></button>`).join('')}</nav>`}
function top(){return `<header class="top"><div class="brand"><div class="logo">SG</div><div><h1>ScamGuard</h1><p>AI-skydd för telefonbedrägerier</p></div></div><div class="pill">Platform v0.3.1 · Dashboard Experience</div></header>`}
function item({icon='•', title, desc, badge, cls='low'}){return `<div class="item"><div class="ico">${icon}</div><div style="flex:1"><h4>${title}</h4><p>${desc}</p></div>${badge?`<span class="badge ${cls}">${badge}</span>`:''}</div>`}
function home(){return `<section class="page active" id="page-home"><div class="hero"><div class="card statusHero"><div class="eyebrow">Skydd aktivt</div><h2>Allt ser tryggt ut idag.</h2><p class="muted">Okända samtal screenas av ScamGuard innan de når Ingrid. Vid risk blockeras samtalet och anhöriga får en tydlig varning.</p><div class="bigrow"><div class="metric"><b>3</b><span>screenade idag</span></div><div class="metric"><b>0</b><span>högrisk idag</span></div><div class="metric"><b>7</b><span>blockerade denna vecka</span></div></div></div><div class="card side"><div class="shield">✓</div><h3>Skyddsnivå: Stark</h3><p class="muted">Okända nummer screenas. Bank, polis och BankID-mönster blockeras automatiskt.</p><div class="progress" style="margin:18px 0 10px"><div class="bar" style="width:86%"></div></div><p class="muted">86% konfigurerat · Lägg till en extra anhörig för maximalt skydd.</p></div></div><div class="grid3 section"><div class="card"><h3>AI-status</h3>${item({icon:'AI',title:'Screeningmotor online',desc:'Mockad analys aktiv. Redo för telefoniadapter senare.',badge:'Online'})}</div><div class="card"><h3>Telefonstatus</h3>${item({icon:'☎',title:'Vidarekoppling simulerad',desc:'Flödet visar hur koppling kommer fungera i pilot.',badge:'Demo',cls:'med'})}</div><div class="card"><h3>Familj</h3>${item({icon:'👥',title:'3 anhöriga kopplade',desc:'Anna är primär kontakt vid högriskvarningar.',badge:'Aktiv'})}</div></div><div class="grid2 section"><div class="card"><div class="split"><h3>Senaste händelser</h3><button class="btn secondary" data-go="calls">Visa alla</button></div><div class="list">${calls.slice(0,3).map(c=>item({icon:c.icon,title:c.title,desc:c.desc,badge:c.risk,cls:c.cls})).join('')}</div></div><div class="card"><h3>Rekommendationer</h3><div class="list">${item({icon:'1',title:'Lägg till reservkontakt',desc:'Ökar chansen att någon ser högriskvarningar snabbt.',badge:'Viktigt',cls:'med'})}${item({icon:'2',title:'Verifiera betrodda nummer',desc:'Lägg in vårdcentral, hemtjänst och familj som alltid tillåtna.',badge:'Nästa'})}${item({icon:'3',title:'Testa ett simulerat samtal',desc:'Visar familjen exakt hur ScamGuard agerar vid risk.',badge:'Demo'})}</div></div></div></section>`}
function protection(){return `<section class="page" id="page-protection"><div class="pageTitle"><h2>Skydd</h2><p>Inställningar för hur okända samtal ska hanteras.</p></div><div class="grid2"><div class="card"><h3>Regler</h3><div class="list">${['Screena alla okända nummer','Blockera BankID- och bankmönster','Notifiera anhörig vid hög risk','Släpp igenom betrodda kontakter'].map((t,i)=>`<div class="item"><div class="ico">${i+1}</div><div style="flex:1"><h4>${t}</h4><p>Aktiverad i demo-läge.</p></div><div class="switch"></div></div>`).join('')}</div></div><div class="card"><h3>Vidarekoppling</h3><p class="muted">I den riktiga tjänsten kommer användaren aktivera villkorad vidarekoppling till ScamGuards nummer. Här visas flödet på ytan.</p><div class="list" style="margin-top:14px">${item({icon:'✓',title:'ScamGuard-nummer reserverat',desc:'+46 8 000 00 000',badge:'Mock'})}${item({icon:'→',title:'Okända samtal går till AI först',desc:'AI screenar innan samtalet kopplas vidare.',badge:'Planerat',cls:'med'})}</div><button class="btn" style="margin-top:16px">Starta installationsguide</button></div></div></section>`}
function callsPage(){return `<section class="page" id="page-calls"><div class="pageTitle"><h2>Samtal</h2><p>Historik över screenade, blockerade och godkända samtal.</p></div><div class="card"><div class="timeline list">${calls.map(c=>item({icon:c.icon,title:`${c.time} · ${c.title}`,desc:c.desc,badge:c.risk,cls:c.cls})).join('')}</div></div></section>`}
function familyPage(){return `<section class="page" id="page-family"><div class="pageTitle"><h2>Anhöriga</h2><p>Personer som får varningar och kan hjälpa till vid misstänkta samtal.</p></div><div class="grid3">${family.map(f=>`<div class="card"><div class="ico" style="width:54px;height:54px;border-radius:19px;font-weight:800">${f.icon}</div><h3 style="margin-top:16px">${f.name}</h3><p class="muted">${f.role}</p><span class="badge low">${f.status}</span></div>`).join('')}</div><div class="card section"><h3>Lägg till anhörig</h3><div class="grid2"><input class="input" placeholder="Namn"><input class="input" placeholder="Mobilnummer"><button class="btn">Skicka inbjudan</button><button class="btn secondary">Visa roller</button></div></div></section>`}
function reports(){return `<section class="page" id="page-reports"><div class="pageTitle"><h2>Rapport</h2><p>Översikt över hur ScamGuard har skyddat familjen senaste 30 dagarna.</p></div><div class="grid3"><div class="card metric"><b>42</b><span>screenade samtal</span></div><div class="card metric"><b>11</b><span>blockerade risker</span></div><div class="card metric"><b>0</b><span>missade högrisk</span></div></div><div class="card section"><h3>Månadens insikt</h3><p class="muted">De vanligaste riskmönstren var falska bankärenden, falsk teknisk support och leveranslänkar. Nästa version får djupare rapporter och filtrering.</p></div></section>`}
function render(){app.innerHTML=`<main class="shell">${top()}${home()}${protection()}${callsPage()}${familyPage()}${reports()}<p class="footerNote">ScamGuard Platform v0.3.1 · mockad produktupplevelse · inga externa kopplingar</p></main>${nav()}`;bind()}
function bind(){document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>show(b.dataset.page));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>show(b.dataset.go));}
function show(id){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));document.querySelector(`#page-${id}`).classList.add('active');document.querySelectorAll('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===id));scrollTo({top:0,behavior:'smooth'});}
render();
