const profile={name:'Björn',protectedPerson:'Ingrid Svensson',status:'Skydd aktivt',protectionScore:94};
const metrics=[['18','Screenade samtal','+22%'],['3','Blockerade risker','+1'],['4','Anhöriga aktiva','100%'],['2.4s','Svarstid AI','stabilt']];
const calls=[{from:'+46 70 118 22 91',label:'Okänt nummer',time:'Idag 10:42',risk:'high',result:'Blockerat',reason:'Påstod sig ringa från banken och bad om BankID.'},{from:'Vårdcentralen',label:'Verifierad vård',time:'Igår 14:12',risk:'low',result:'Släppt igenom',reason:'Matchade betrodd kategori och tryggt samtalsmönster.'},{from:'+46 8 502 300 11',label:'Okänd fast telefon',time:'Mån 16:03',risk:'medium',result:'Screenat',reason:'AI frågade ärende innan koppling.'}];
const family=[['Anna','Dotter','Aktiv','Alla högrisk'],['Erik','Son','Aktiv','Endast akuta'],['Maja','Barnbarn','Reserv','Veckorapport']];
const activity=[['Högrisk-samtal stoppat','AI:n avbröt samtalet innan det kopplades till Ingrid.','10:42'],['Anhörig notifierad','Anna fick en trygghetsnotis med sammanfattning.','10:43'],['Skyddsnivå kontrollerad','Alla okända nummer screenas innan vidarekoppling.','08:00']];
const pages=[['dashboard','Hem'],['protection','Skydd'],['calls','Samtal'],['family','Familj'],['reports','Rapporter'],['installation','Installation'],['settings','Inställningar'],['support','Support']];
const nav=[['dashboard','Hem','🛡️'],['protection','Skydd','🔒'],['calls','Samtal','☎️'],['family','Familj','👥']];
let page='dashboard';
const root=document.getElementById('root');
const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const section=(title,body,action='')=>`<section class="section"><div class="sectionHead"><h2>${title}</h2>${action?`<span class="link">${action}</span>`:''}</div>${body}</section>`;
const row=(icon,title,text,meta='')=>`<div class="row"><div class="ico">${icon}</div><div><h3>${esc(title)}</h3><p>${esc(text)}</p></div>${meta?`<div class="meta">${esc(meta)}</div>`:''}</div>`;
const stat=m=>`<div class="stat"><b>${m[0]}</b><span>${m[1]}</span><small>${m[2]}</small></div>`;
const badge=r=>`<span class="badge ${r}">${r==='high'?'Hög risk':r==='medium'?'Medel':'Låg risk'}</span>`;
const callRow=c=>`<div class="row"><div class="ico">☎️</div><div style="flex:1"><h3>${esc(c.label)}</h3><p>${esc(c.from)} · ${esc(c.result)}</p><p>${esc(c.reason)}</p></div><div style="display:grid;gap:7px;justify-items:end">${badge(c.risk)}<span class="meta">${esc(c.time)}</span></div></div>`;
const header=(title,text)=>`<div class="eyebrow">Kontrollpanel</div><h1 class="title">${esc(title)}</h1><p class="subtitle">${esc(text)}</p>`;
const topbar=()=>`<div class="topbar"><div class="brand"><div class="logo">SG</div><div><div class="eyebrow">ScamGuard</div><div style="font-weight:850">Platform v0.3</div></div></div><div class="ico">🔔</div></div>`;
const hero=()=>`<div class="card hero"><div class="heroTop"><div><span class="pill"><i class="dot"></i> ${profile.status}</span><h1 class="title">${profile.protectedPerson} är skyddad</h1><p class="subtitle" style="color:#235047">Okända samtal screenas av ScamGuard innan de kopplas vidare.</p></div><div class="score">${profile.protectionScore}<small>%</small></div></div><div class="progress mt"><i style="width:${profile.protectionScore}%"></i></div></div>`;
const toggles=items=>`<div class="card">${items.map(([a,b])=>`<div class="formrow"><div><h3 style="margin:0 0 4px;font-size:15px">${esc(a)}</h3><p class="muted" style="margin:0;font-size:13px">${esc(b)}</p></div><div class="switch"></div></div>`).join('')}</div>`;
function dashboard(){return header(`Hej ${profile.name}`,'Allt ser lugnt ut. ScamGuard arbetar i bakgrunden och screenar okända samtal innan de når Ingrid.')+hero()+section('Senaste veckan',`<div class="grid">${metrics.map(stat).join('')}</div>`,'Visa rapport')+`<div class="actions"><button class="btn primary">🛡️ Skydd aktivt</button><button class="btn ghost">☎️ Simulera samtal</button></div>`+section('Senaste händelser',`<div class="list">${activity.map(a=>row('✅',a[0],a[1],a[2])).join('')}</div>`,'Alla')+section('Senaste samtal',`<div class="list">${calls.slice(0,2).map(callRow).join('')}</div>`)}
function protection(){return header('Skydd','Här styrs hur samtal screenas, vilka som släpps igenom och när anhöriga ska få en varning.')+toggles([['Screena alla okända samtal','Okända nummer går till ScamGuard innan Ingrid störs.'],['Släpp igenom betrodda kontakter','Familj, vård och sparade kontakter kopplas direkt.'],['Blockera högrisk automatiskt','Bedrägerimönster stoppas utan att kopplas vidare.'],['Anhörigvarning vid risk','Anna får notis med sammanfattning vid hög risk.']])+section('Skyddsnivå',`<div class="card"><div class="pill"><i class="dot"></i> Rekommenderat läge</div><h2 style="margin:14px 0 6px">Trygg balans</h2><p class="muted">Screenar okända samtal men minimerar risken att viktiga samtal stoppas.</p></div>`)}
function callsPage(){return header('Samtal','Historik över screenade, blockerade och vidarekopplade samtal.')+`<div class="list mt">${calls.map(callRow).join('')}</div>`+section('AI-bedömning',`<div class="card">${row('📊','Beslutskedja','Nummeranalys → ärendefråga → riskord → vidarekoppling eller blockering.')}${row('🛡️','Nästa steg','I kommande release får varje samtal en detaljerad tidslinje och transkription.')}</div>`)}
function familyPage(){return header('Anhöriga','Familjen är ScamGuards viktigaste skyddsnät. Här styrs roller och notifieringar.')+`<div class="list mt">${family.map(f=>row('🤝',`${f[0]} · ${f[1]}`,`${f[2]}. Notiser: ${f[3]}`,'Hantera')).join('')}</div>`+section('Prioritet',`<div class="card"><p class="muted" style="margin-top:0">Vid högrisk kontaktas anhöriga i prioriterad ordning. Om första personen inte kvitterar kan nästa anhörig varnas.</p><button class="btn primary">👥 Lägg till anhörig</button></div>`)}
function reports(){return header('Rapporter','Översikt över skyddets effekt över tid.')+`<div class="grid mt">${[['18','Screenade','30 dagar'],['3','Blockerade','Hög risk'],['0','Missade','Rapporterade'],['94%','Skyddspoäng','Stabilt']].map(stat).join('')}</div>`+section('Insikt',`<div class="card"><h2 style="margin-top:0">Bankbedrägerier dominerar</h2><p class="muted">2 av 3 blockerade högrisk-samtal innehöll hänvisningar till bank, BankID eller brådskande verifiering.</p></div>`)}
function installation(){return header('Installation','Guiden som senare kopplar telefonnummer, vidarekoppling och anhörigkonto.')+`<div class="card">${row('✅','Konto skapat','Administratör och seniorprofil är redo.')}${row('✅','Anhörig tillagd','Anna får varningar vid högrisk.')}${row('🛠️','Vidarekoppling','Mockad i denna version. Senare kopplas telefoni-adapter.')}</div>`}
function settings(){return header('Inställningar','Konton, språk, notiser, abonnemang och dataskydd.')+toggles([['Veckorapport','Skicka lugn summering varje söndag.'],['Diskret läge','Minimera störande notiser för senioren.'],['Dela data med anhöriga','Visa endast risker och sammanfattningar.']])}
function support(){return header('Support','Hjälp för seniorer och anhöriga.')+`<div class="card"><h3 style="margin:0 0 6px">Trygg hjälp, utan teknikstress</h3><p class="muted" style="margin:0">Här kommer guider, vanliga frågor och möjlighet att kontakta ScamGuard-support.</p></div>`}
function body(){return ({dashboard,protection,calls:callsPage,family:familyPage,reports,installation,settings,support}[page]||dashboard)()+section('Fler delar',`<div class="list">${pages.filter(p=>!nav.some(n=>n[0]===p[0])).map(p=>`<button data-page="${p[0]}" class="row navlink" style="width:100%;color:inherit;text-align:left;cursor:pointer"><div class="ico">›</div><div><h3>${p[1]}</h3><p>Öppna ${p[1].toLowerCase()}.</p></div></button>`).join('')}</div>`)}
function render(){root.innerHTML=`<div class="app"><main class="phone"><div class="content">${topbar()}${body()}</div><nav class="nav">${nav.map(n=>`<button data-page="${n[0]}" class="${page===n[0]?'active':''}"><span style="font-size:18px">${n[2]}</span><span>${n[1]}</span></button>`).join('')}</nav></main></div>`;document.querySelectorAll('[data-page]').forEach(b=>b.addEventListener('click',()=>{page=b.dataset.page;render();scrollTo({top:0,behavior:'smooth'});}));}
render();
